var GAME_LEVELS = [
  ["              b                  b                  g                           ",
   "                                                                                ",
   "                                                o                               ",
   "                                                                                ",
   "                                               xxx                              ",
   "                                                 x  o          o                ",
   "                                                 x                              ",
   "                                          xxxx   x  o   xx  o  xx               ",
   "                                    o o          x       xu    x        o       ",
   "                                 o               xxxxx   xxxxxxx                ",
   "                            o o    xxxxx                               xxx      ",
   "                   o                        o                                   ",
   "              o            xxxxx                                                ",
   "                   xx                     xxxxx                                 ",
   "              xx                                  o                        o    ",
   "                                                                                ",
   "   @                                                    o                       ",
   "xxxxxxxxxxxxx                           xxxxxxxxxxxxxx  o  xxxxxxx      xxxxxxxx",
   "xxxxxxxxxxxxx         xxxxxxxxxxxx      xxxxxxxxxxxxxx  o  xxxxxxx      xxxxxxxx",
   "                      xxxxxxxxxxxx      xxxxxxxxxxxxxxu    xxxxxxx              ",
   "                                        xxxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "                                        xxxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "                                                                                ",
   "                                                                                "],
  ["                                         g           b                  g                                     ",
   "            xxxxxxxxxxxxxxxxxxxxxxx                                                    o   xxxxxxxxxxxxxxxxxxx",
   "            x                     x                                                                           ",
   "            x                     x                                                    o           o          ",
   "            x o                 o x                                                                     o     ",
   "            x                     x                                                  xxxxx       xxxxx        ",
   "            xxxxx             xxxxx                                                  x   x                o   ",
   "            x           o         x                                            o o   x   x                    ",
   "            xu  o                 x      o                  xxxxxxxx                 x   xxxxx          xxxxxx",
   "            x      xxxxxxxxxx     x    o   o                x   g       o     xxxxx  x                        ",
   "            x               x     x                         x                        x         o    x         ",
   "            x   o           x     x   xxxxxxx               x         xxxxx          x                  o     ",
   "            x               x                        o      x                        x      xxxxxx            ",
   "            xxxxxxxxx       xu                              x o                      x                  o     ",
   "                    xxx     xxxxxxxxxx       xxxxxxx        x       xxxxxxxxxxx      x                        ",
   "                    x       x                      x o      xxx               x      xxxxxxx        xxxxxxxxxx",
   "                    x     xxx                      x        x                 x      x              x<<<<<<<<<",
   "             xxxxxxxx       x                      xxxxx    x                ox      x  o           x<<<<<<<<<",
   "             x          o   x                      x        xxxxxxxxx         x      x     xxxxxx   r<<<<<<<<<",
   "             x              x                      x      o         x       xxx      x     x<<<<<<<<<<<<<<<<<<",
   "             x   o xxxxxxxxxx                      xu               x    o    x      x     r<<<<<<<<<<<<<<<<<<",
   "xxxxxxxxxxxxxx     x                               xxxxxxxxxxxx     x         x      x     xxxxxxxxxxxxxxxxxxx",
   "                 xxx                                          x     x   xxxxxxx      x                        ",
   "                   x                                          x               x      x              o     o   ",
   "   @               x                                          xu              x      x                        ",
   "xxxxxxxxxxxxxxxxxxxx                                          xxxxxxxxx     xxx      xxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                   g x<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x     b                                      xxxxx xxxxx  ",
   "                                      x<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x                                             x<<<x x<<<x  ",
   "                                       x<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x                                              x<<<x x<<<x  ",
   "                                        x<<<<<<<xxxxx<<<<<<<<<<<<<<xxxxx<<<<<<<x                                               x<<x x x<<x  ",
   "                                         x<<<<<x     x<<<<<<<<<<<<x     x<<<<<x                                                x<x x x x<x  ",
   "  @                                       x<<<x       x<<<<<<<<<<x       x<<<x                                                 xnx  x  xnx  ",
   "xxxx      o                                xnx         xnxxnnxxnx         xnx                             o                                 ",
   "xxxx      o xxx                                                                                       xxxx o                                ",
   "u           xg  o                                                                                     xg x                                  ",
   "        xxxxx                                                                     o           o       x  xxxxx                              ",
   "            x  xxx                                                                                 xxxx      xxxx                           ",
   "            x   o   xxx                                                          xxx         xxx                x o                         ",
   "            xu      x                                                            xgx         x x                x                           ",
   "            xxxxxxxxx         o                                                    x         x    xx   o        x o                 o       ",
   "                        o                                                    x     xx   xx   x                  x                           ",
   "                        o   xxxxx                            o                     x         x   o    xxx       xxxx               xxx      ",
   "                                                              o      x   x         o         x                     x          o             ",
   "                      xxxxx      xxxx       o           x            x   x o x                  xxx                xx                       ",
   "r                                   x       o              xxxxxx    x   x   xxxxxxxxx       x                   xxx         xxx            ",
   "                xxxx                x             xxxx               x   x o x    o o   xxx  x                   x                          ",
   "             oo                     x     xxxxx o o  x               x   x   xu              x                   x                          ",
   "r                                  rxu               x               x   xxxxx   xxxxxx      x                   x    o       o          o  ",
   "             xx                     x          xxxx  x               x                       x                  xx           o              ",
   "                                    xxx              x               x                       x                  xg  xxxxx                ox ",
   "                                                                                                                x           xxxx          x<",
   "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x           x<<xu       xxx<",
   "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<xx  o   xxxxxx<<xxxxx  xxxx<<",
   "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x       x<<<<<<<<<<<<<<<<<<<<",
   "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<xu      x<<<<<<<<<<<<<<<<<<<<",
   "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<xxxxxxxxx<<<<<<<<<<<<<<<<<<<<"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
